package AbsentStudent;
// Generated Sep 30, 2021 10:24:13 PM by Hibernate Tools 4.3.1

import NilaiSiswa.Nilai_Siswa;
import java.util.List;
import javax.faces.bean.ManagedBean;




/**
 * TblNilaisiswa generated by hbm2java
 */
@ManagedBean
public class TblNilaisiswa  implements java.io.Serializable {


     private int idSiswa;
     private String nomorSiswa;
     private String kelas;
     private String namaSiswa;
     private String tanggalKehadiran;
     private String mataPelajaran;
     private String nilai;
     
    public void save_nilaisiswa()
    {
        Nilai_Siswa add = new Nilai_Siswa();
        add.add_nilaisiswa(this);
    }
     
    public List<TblNilaisiswa> getAllRecords()
    {
        Nilai_Siswa stud = new Nilai_Siswa();
        List<TblNilaisiswa> iStud = stud.retrieveTblNilaisiswa();
        return iStud;
    }
     
    public String getById()
    {
        String id_siswa = Integer.toString(idSiswa);
        Nilai_Siswa stud = new Nilai_Siswa();
        List<TblNilaisiswa> stud1 = stud.getbyID(id_siswa);
        try {
            if (stud1 != null) {
                idSiswa = stud1.get(0).idSiswa;
                nomorSiswa = stud1.get(0).nomorSiswa;
                kelas = stud1.get(0).kelas;
                namaSiswa = stud1.get(0).namaSiswa;
                tanggalKehadiran = stud1.get(0).tanggalKehadiran;
                mataPelajaran = stud1.get(0).mataPelajaran;
                nilai = stud1.get(0).nilai;
                return "Nilai Siswa";
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        return "Failed Search Nilai Siswa";
    }
    
    public String editnilaiSiswa()
    {
        Nilai_Siswa stud = new Nilai_Siswa();
        stud.editnilaiSiswa(this);
        idSiswa = 0;
        nomorSiswa = "";
        kelas = "";
        namaSiswa = "";
        tanggalKehadiran = "";
        mataPelajaran = "";
        nilai = "";
        return "Nilai Siswa";
    }
    
    public String deletenilaiSiswa()
    {
        //String id_siswa = Integer.toString(idSiswa);
        Nilai_Siswa stud = new Nilai_Siswa();
        stud.deletenilaiSiswa(idSiswa);
        idSiswa = 0;
        nomorSiswa = "";
        kelas = "";
        namaSiswa = "";
        tanggalKehadiran = "";
        mataPelajaran = "";
        nilai = "";
        return "Nilai Siswa";
    }

    public TblNilaisiswa() {
    }

    public TblNilaisiswa(int idSiswa, String nomorSiswa, String kelas, String namaSiswa, String tanggalKehadiran, String mataPelajaran, String nilai) {
       this.idSiswa = idSiswa;
       this.nomorSiswa = nomorSiswa;
       this.kelas = kelas;
       this.namaSiswa = namaSiswa;
       this.tanggalKehadiran = tanggalKehadiran;
       this.mataPelajaran = mataPelajaran;
       this.nilai = nilai;
    }
   
    public int getIdSiswa() {
        return this.idSiswa;
    }
    
    public void setIdSiswa(int idSiswa) {
        this.idSiswa = idSiswa;
    }
    public String getNomorSiswa() {
        return this.nomorSiswa;
    }
    
    public void setNomorSiswa(String nomorSiswa) {
        this.nomorSiswa = nomorSiswa;
    }
    public String getKelas() {
        return this.kelas;
    }
    
    public void setKelas(String kelas) {
        this.kelas = kelas;
    }
    public String getNamaSiswa() {
        return this.namaSiswa;
    }
    
    public void setNamaSiswa(String namaSiswa) {
        this.namaSiswa = namaSiswa;
    }
    public String getTanggalKehadiran() {
        return this.tanggalKehadiran;
    }
    
    public void setTanggalKehadiran(String tanggalKehadiran) {
        this.tanggalKehadiran = tanggalKehadiran;
    }
    public String getMataPelajaran() {
        return this.mataPelajaran;
    }
    
    public void setMataPelajaran(String mataPelajaran) {
        this.mataPelajaran = mataPelajaran;
    }
    public String getNilai() {
        return this.nilai;
    }
    
    public void setNilai(String nilai) {
        this.nilai = nilai;
    }



}


